zsh: Adding antidote and sheldon option plugins managers

diff --git a/stow-files-home/dot-zshrc b/stow-files-home/dot-zshrc
--- a/stow-files-home/dot-zshrc
+++ b/stow-files-home/dot-zshrc
@@ -17,6 +17,12 @@ setopt HIST_SAVE_NO_DUPS       # do not save duplicated command
 setopt HIST_REDUCE_BLANKS      # remove unnecessary blanks
 setopt INC_APPEND_HISTORY_TIME # append command to history file immediately after execution
 setopt EXTENDED_HISTORY        # record command start time
+# Plugin Manager Configuration
+# Set to 'zplug', 'antidote', or 'sheldon' to choose plugin manager
+# Examples:
+#   export ZSH_PLUGIN_MANAGER=zplug
+#   export ZSH_PLUGIN_MANAGER=sheldon
+export ZSH_PLUGIN_MANAGER=${ZSH_PLUGIN_MANAGER_OVERRIDE:-antidote}
 
 export ZPLUG_HOME=${HOME}/.zplug
 # export ZPLUG_VERSION=2.4.2
@@ -26,6 +32,33 @@ function load_zplug() {
     curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/main/installer.zsh | zsh
   fi
   source $ZPLUG_FILE
+}
+
+# Antidote - Modern, fast zsh plugin manager
+export ANTIDOTE_HOME=${HOME}/.antidote
+function load_antidote() {
+  if [ ! -d $ANTIDOTE_HOME ]; then
+    echo 'Installing antidote...'
+    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ANTIDOTE_HOME}
+  fi
+  # echo "Loading antidote"
+  source ${ANTIDOTE_HOME}/antidote.zsh
+}
+
+# Sheldon - Fast, configurable shell plugin manager
+export SHELDON_CONFIG_DIR=${HOME}/.config/sheldon
+export SHELDON_CONFIG_FILE=${SHELDON_CONFIG_DIR}/plugins.toml
+function load_sheldon() {
+  if ! command -v sheldon &>/dev/null; then
+    echo 'sheldon not found. Install via: cargo install sheldon or download from https://github.com/rossmacarthur/sheldon/releases'
+    return 1
+  fi
+  if [ ! -f $SHELDON_CONFIG_FILE ]; then
+    echo 'Initializing sheldon config...'
+    mkdir -p $SHELDON_CONFIG_DIR
+    sheldon init --shell zsh
+  fi
+  eval "$(sheldon source)"
 }
 
 bind_keys() {
@@ -115,6 +148,88 @@ function apply_zplug_bundles() {
   fi
 }
 
+# Antidote bundle configuration - generates .zsh_plugins.txt
+function apply_antidote_bundles() {
+  if ! command -v antidote &>/dev/null; then
+    return 1
+  fi
+
+  #   local plugins_file="${ZDOTDIR:-$HOME}/.zsh_plugins.txt"
+  #
+  #   # Only regenerate if plugins file doesn't exist or if forced
+  #   if [[ ! -f $plugins_file ]] || [[ -v ANTIDOTE_REGENERATE ]]; then
+  #     echo 'Generating antidote plugins file...'
+  #     cat >$plugins_file <<'EOF'
+  # # Antidote plugins file - generated by dot-zshrc
+  # # Core plugins
+  # zsh-users/zsh-history-substring-search
+  #
+  # # gmatheu/shell-plugins subdirectories
+  # gmatheu/shell-plugins path:dirrc
+  # gmatheu/shell-plugins path:git
+  # gmatheu/shell-plugins path:notify
+  # gmatheu/shell-plugins path:vim
+  # gmatheu/shell-plugins path:clipboard
+  # gmatheu/shell-plugins path:grep
+  # gmatheu/shell-plugins path:fast-server
+  # gmatheu/shell-plugins path:quick-file-actions
+  # gmatheu/shell-plugins path:profile-secrets
+  # gmatheu/shell-plugins path:fzf
+  # gmatheu/shell-plugins path:version-managers
+  # gmatheu/shell-plugins path:password-store
+  # gmatheu/shell-plugins path:file-compression
+  # gmatheu/shell-plugins path:gcloud
+  # gmatheu/shell-plugins path:kubectl
+  # gmatheu/shell-plugins path:aws
+  # gmatheu/shell-plugins path:rclone-fzf
+  # gmatheu/shell-plugins path:telegram
+  # gmatheu/shell-plugins path:ssh-agent
+  # gmatheu/shell-plugins path:zplug-helper
+  # gmatheu/shell-plugins path:npm-scripts
+  # gmatheu/shell-plugins path:tmux
+  # gmatheu/shell-plugins path:ripgrep
+  #
+  # # Other plugins
+  # gmatheu/dotfiles path:shell-plugin
+  # nix-community/nix-zsh-completions
+  #
+  # # Oh-My-Zsh plugins (loaded as paths)
+  # ohmyzsh/ohmyzsh path:plugins/docker-compose
+  # ohmyzsh/ohmyzsh path:plugins/gcloud
+  # ohmyzsh/ohmyzsh path:plugins/git
+  # ohmyzsh/ohmyzsh path:plugins/git-extras
+  # ohmyzsh/ohmyzsh path:plugins/pip
+  # ohmyzsh/ohmyzsh path:plugins/rvm
+  # ohmyzsh/ohmyzsh path:plugins/pyenv
+  # ohmyzsh/ohmyzsh path:plugins/debian
+  # ohmyzsh/ohmyzsh path:plugins/history
+  # ohmyzsh/ohmyzsh path:plugins/history-substring-search
+  # ohmyzsh/ohmyzsh path:plugins/command-not-found
+  # ohmyzsh/ohmyzsh path:plugins/common-aliases
+  # ohmyzsh/ohmyzsh path:plugins/asdf
+  #
+  # # Theme and extras
+  # chriskempson/base16-shell
+  # EOF
+  #
+  #     # Add spaceship theme if not using starship
+  #     if [[ ! -v USE_STARSHIP ]]; then
+  #       echo 'spaceship-prompt/spaceship-prompt' >>$plugins_file
+  #     fi
+  #   fi
+
+  antidote load
+}
+
+# Sheldon bundle configuration - generates plugins.toml
+function apply_sheldon_bundles() {
+  if ! command -v sheldon &>/dev/null; then
+    return 1
+  fi
+
+  eval "$(sheldon source)"
+}
+
 function extra_init() {
   d=~/.dircolors
   test -r $d && eval "$(dircolors $d)"
@@ -173,12 +288,38 @@ export PATH=$EGET_BIN:$PATH
 
 eval "$(zoxide init zsh)"
 
-if [[ -v SKIP_ZPLUG ]]; then
-  echo "Skipping zplug use apply_zplug_bundles to load plugins"
-else
-  load_zplug
-  apply_zplug_bundles
-fi
+# Plugin Manager Loading Logic
+load_plugins() {
+  case "${ZSH_PLUGIN_MANAGER}" in
+  antidote)
+    if [[ -v SKIP_ANTIDOTE ]]; then
+      echo "Skipping antidote (SKIP_ANTIDOTE is set)"
+    else
+      load_antidote
+      apply_antidote_bundles
+    fi
+    ;;
+  sheldon)
+    if [[ -v SKIP_SHELDON ]]; then
+      echo "Skipping sheldon (SKIP_SHELDON is set)"
+    else
+      load_sheldon
+      apply_sheldon_bundles
+    fi
+    ;;
+  zplug | *)
+    # Default to zplug for backward compatibility
+    if [[ -v SKIP_ZPLUG ]]; then
+      echo "Skipping zplug (SKIP_ZPLUG is set)"
+    else
+      load_zplug
+      apply_zplug_bundles
+    fi
+    ;;
+  esac
+}
+
+load_plugins
 if [[ -v USE_STARSHIP ]]; then
   echo "[experimental] Using starship as zsh prompt"
   eval "$(starship init zsh)"
@@ -279,6 +420,6 @@ export LS_COLORS=$(vivid generate dracula)
 zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
 # source <(carapace _carapace)
 
-# compdef _files _nvim
+compdef _files _nvim
 # autoload -U compinit
 # compinit
